best_params:
  batch_size: 16
  dropout_rate: 0.2580503754609679
  num_layers_to_use: 1
  optimizer_type: adamw
  use_multilayer: false
  weight_decay: 0.007369075727995949
best_value: 0.9388
classifier_type: bilstm
metric: f1_macro
test_results:
  eval_accuracy: 0.9303
  eval_f1_macro: 0.9279
  eval_loss: 0.3653
  eval_matthews_correlation: 0.9127
  eval_precision: 0.9296
  eval_recall: 0.9268
training_metadata:
  architecture:
    classifier_type: bilstm
    dropout_rate: 0.2580503754609679
    num_layers_to_use: 1
    use_multilayer: false
  batch_size: 16
  optimizer: adamw
  timestamp: 2025-03-16 19:10:49 GMT+10
