best_params:
  batch_size: 16
  dropout_rate: 0.18507579583946976
  num_layers_to_use: 1
  optimizer_type: adamw
  use_multilayer: false
  weight_decay: 0.002285910147105054
best_value: 0.9603
classifier_type: cnn
metric: f1_macro
test_results:
  eval_accuracy: 0.9461
  eval_f1_macro: 0.9433
  eval_loss: 0.2368
  eval_matthews_correlation: 0.9324
  eval_precision: 0.9444
  eval_recall: 0.9424
training_metadata:
  architecture:
    classifier_type: cnn
    dropout_rate: 0.18507579583946976
    num_layers_to_use: 1
    use_multilayer: false
  batch_size: 16
  optimizer: adamw
  timestamp: 2025-03-16 12:36:36 GMT+10
