best_params:
  batch_size: 16
  dropout_rate: 0.21475341021205646
  learning_rate: 0.0012468565158976787
  num_layers_to_use: 4
  num_wavelets: 64
  optimizer_type: adamw
  use_multilayer: true
  warmup_ratio: 0.14266748141681462
  wavelet_type: mixed
  weight_decay: 0.006017930698034895
best_value: 0.9087
classifier_type: wavelet_kan
metric: f1_macro
training_metadata:
  architecture:
    classifier_type: wavelet_kan
    dropout_rate: 0.21475341021205646
    num_layers_to_use: 4
    use_multilayer: true
  batch_size: 16
  optimizer: adamw
  timestamp: 2025-03-16 17:04:28 GMT+10
